package com.ita.training.java.exceptions;

public class RuntimeExceptionDemo {
	
	
	public static void main(String[] args) {
		
		int numArray[] = new int[2];
		
		numArray[0] = 10;
		numArray[1]	= 20;
		
		System.out.println(numArray[0] + " and " + numArray[1] +"is stored in array");
	}

}
